[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-first-ci-cd"
version = "0.1.0"
description = "my-first-ci-cd"
authors = [{ name="semen", email="semenhvor@gmail.com" }]
dependencies = [
    "Flask>=3.1.2",
]