name: CI/CD Pipeline with SAST

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настраиваем окружение Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Устанавливаем зависимост
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit pytest

      # 4. Запускаем SAST (Bandit)
      - name: Run Bandit SAST Scan
        run: |
          bandit -r . --severity-level high --confidence-level high -f json -o bandit_results.json || true

      # 4.1. Анализируем отчёт Bandit, падение при HIGH/HIGH
      - name: Check Bandit Results
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          if [ -f bandit_results.json ]; then
            if jq -e '.results[] | select(.issue_confidence == "HIGH" and .issue_severity == "HIGH")' bandit_results.json > /dev/null; then
              echo "Bandit found critical vulnerabilities! Failing the pipeline."
              exit 1
            else
              echo "No critical HIGH/HIGH vulnerabilities found by Bandit."
            fi
          else
            echo "Bandit report not found. Assuming no issues."
          fi

      # 4.2. Сохранение артефакта Bandit (Задание №1)
      - name: Upload Bandit artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit_results.json

      # 5.  Запускаем сканер зависимостей Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      # 6. Запускаем наши unit-тесты
      - name: Run Tests with pytest
        run: |
          python -m pytest tests/ -v

